services:
  baresip-ivr:
    image: imansur/baresip-ivr:latest
    container_name: baresip_ivr
    network_mode: "host"             # SIP + RTP için zorunlu
    restart: unless-stopped

    volumes:
      - ./app:/app/app:ro
      - ./voices:/app/voices:ro
      - ./config:/root/.baresip/config:ro
      - ./accounts:/root/.baresip/accounts:ro

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
